#include "postprocess.h"
#include <vector>
#include <fstream>

void PostProcess::WriteVTKCollocated_temp(
     StructureMesh& mesh, std::string filename)
{
    cellnum = mesh.cellnum_export();
    nodenum = mesh.nodenum_export();
    
    x_nodes = mesh.xnodes_export();
    y_nodes = mesh.ynodes_export();
    z_nodes = mesh.znodes_export();

    t = mesh.tfield_export();

    std::ofstream vtkFile(filename);
    if(!vtkFile.is_open())
    {
        std::cerr << "Error: Cannot open file " << filename << std::endl;
        return;
    }

    // ========== 写入 VTK 头部信息 ==========
    vtkFile << "# vtk DataFile Version 3.0\n";
    vtkFile << "VTK file generated by C++ code\n";
    vtkFile << "ASCII\n";
    vtkFile << "DATASET RECTILINEAR_GRID\n";

    // ========== 写入网格信息 ==========
    vtkFile << "DIMENSIONS " << nodenum[0] << " " << nodenum[1] << " " << nodenum[2] << "\n";
    vtkFile << "X_COORDINATES " << nodenum[0] << " " << "float\n";
    for(auto& i : x_nodes) {vtkFile << i << " ";}
    vtkFile << "\n";
    vtkFile << "Y_COORDINATES " << nodenum[1] << " " << "float\n";
    for(auto& i : y_nodes) {vtkFile << i << " ";}
    vtkFile << "\n";
    vtkFile << "Z_COORDINATES " << nodenum[2] << " " << "float\n";
    for(auto& i : z_nodes) {vtkFile << i << " ";}
    vtkFile << "\n";

    // ========== 写入单元信息 ==========
    int totalcnum = (nodenum[0] - 1) * (nodenum[1] - 1) * (nodenum[2] - 1);
    vtkFile << "CELL_DATA " << totalcnum << " " << "\n";

    //定义数据块
    vtkFile << "FIELD FieldData 1\n";

    // ========== 写入温度数据 ==========
    vtkFile << "t" << " 1 " << totalcnum << " float\n";
    // 第二行：按 Fortran 顺序展平（手动实现）
    std::vector<float> t_arr;
    t_arr.reserve(totalcnum);
    // Fortran 顺序：k (z) 在最外层
    for (int k = 0; k < cellnum[2]; ++k) {
        for (int j = 0; j < cellnum[1]; ++j) {
            for (int i = 0; i < cellnum[0]; ++i) {
                t_arr.push_back(t[i][j][k]);
            }
        }
    }
    //写入t_arr单行数组
    for (size_t i = 0; i < t_arr.size(); ++i) {
        vtkFile << t_arr[i];
        if (i < t_arr.size() - 1) {
            vtkFile << " ";
        }
    }
    vtkFile << "\n";

    vtkFile.close();
    std::cout << "VTK file written: " << filename << std::endl;
}